# Generated by Django 2.2.20 on 2021-05-04 12:19

from django.conf import settings
from django.db import migrations, models
import ingest.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20210420_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='token',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upload',
            name='blob',
            field=models.FileField(upload_to=ingest.utils.UploadFilenameFactory('bindata')),
        ),
    ]
