# Generated by Django 2.2.20 on 2021-05-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_auto_20210504_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingest.Token'),
        ),
    ]
